### ISSUE TITLE
[BUG] Can't download cources

### ISSUE THREAD

**Issue by alexiszp** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#102]
**Describe the bug**
Hi, I'm a new user and don't have a lot of experience with your application, but was able to download some courses.
But some of them are giving a message that course is downloaded, but downloads only part of it.
Example 
https://www.linkedin.com/learning/microsoft-cybersecurity-architect-expert-sc-100-cert-prep-1-design-a-zero-trust-strategy-and-architecture/what-you-should-know?autoSkip=true&contextUrn=urn%3Ali%3AlyndaLearningPath%3A6372bd3c498ed7b3f9d55969&resume=false&u=107728138

It downloads only module 02 and lection 04
Could you please check it?

**Operating System**
Win10 19045.3803

**Log File**
Upload the latest log file present at `%localappdata%\Linkedin-Learning-Courses-Downloader\app-1.1.0\logs` here.
[log20240120_log.txt](https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/files/13998794/log20240120_log.txt)

**Comment by alexiszp** [comment]
It was resolved, used another solution to download.

**Comment by alexiszp** [comment]
Used another solution

**Comment by Janekpawel** [comment]
> Used another solution

What solution did you use? I am getting the same problem.
