### ISSUE TITLE
incomplete download

### ISSUE THREAD

**Issue by solomonsjoseph** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#11]
I am very happy to use your work to download the courses. It was working fine for some days then later on it started showing the download is complete skipping many videos and courses. I tried to redownload and redo the process but it continues. I hope you see to this issue and come up with a solution that works. 

Also, I was thinking if you could add the author name with the courses then it'll be an addon benefit for all of your users.

Thanks alot.

*Can you help me understand the "enterpriseprofilehash". Because I'm curious about it and it's working.

**Comment by ahmedayman4a** [comment]
Can you give me an example of a course that causes this and upload the logs at `%localappdata%\Linkedin-Learning-Courses-Downloader\app-1.1.0\logs` here.
### As for enterpriseprofilehash :
Some LinkedIn learning organization accounts require a special header (`x-li-identity`) to authorize properly. The value of this header can be found in the JSON inside a code tag in the LinkedIn-learning website. It is named `enterpriseprofilehash` in this JSON. The app extracts it by using the provided token to make a GET request to `https://www.linkedin.com/learning` and matching the enterpriseprofilehash value found in the returned raw HTML text. That way every request is supplied with the proper `x-li-identity` header to prevent any authorization issues.

**Comment by ahmedayman4a** [comment]
Closed due to inactivity
