### ISSUE TITLE
Course Extraction Failed

### ISSUE THREAD

**Issue by Sujit007z** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#19]
Unexpected Character Encountered Wile Parsing Value C.Path ", line 0, position 0

![image](https://user-images.githubusercontent.com/88311340/136196518-aa5b4ebb-7224-47d0-8548-b211472a1d5d.png)

**Comment by ahmedayman4a** [comment]
You are using an expired token. It should work if you use your latest valid token.
