### ISSUE TITLE
my account has been restricted

### ISSUE THREAD

**Issue by mahdisky** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#2]
after login linkdin show message
 "Your account has been restricted"

i used after this app

**Comment by ahmedayman4a** [comment]
Might be a coincidence. Are you using an organization account such as a linkedin learning account provided by a library or a college?

**Comment by mahdisky** [comment]
i get private account

**Comment by ahmedayman4a** [comment]
Did you download a lot of courses before your account got restricted? How many?

**Comment by ahmedayman4a** [comment]
That's odd. I have downloaded like 20 or more and nothing ever happened. Can u contact [linkedin support](https://www.linkedin.com/help/linkedin/ask/gri) and ask them why your account got restricted. Maybe then can help you lift this restriction.

**Comment by ahmedayman4a** [comment]
Any update?

**Comment by ahmedayman4a** [comment]
Issue closed due to inactivity. If you have any update I will reopen it.
