### ISSUE TITLE
Windows Installation Instructions Missing

### ISSUE THREAD

**Issue by arv130kol** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#28]
**Is your feature request related to a problem? Please describe.**
Unable to install this tool on Windows.

**Describe the solution you'd like**
I need a step-by-step process to install this tool on Windows.

**Describe alternatives you've considered**
I did download the windows rar file and extracted it. I got Setup.wxs file inside the directory. Now, how to use that file to perform the installation? I am unable to open that file.

**Additional context**
Adding those steps and some screenshots will help many people use this tool. I checked with a few other folks and no one knows about the WIX file setup.

**Comment by ahmedayman4a** [comment]
There should be a .exe too in the rar file, isn't there?
![Setup rar screenshot](https://user-images.githubusercontent.com/55313946/151809750-c7b009b2-d84d-4116-862a-01c2a6343ba0.png)
