### ISSUE TITLE
Token Failure

### ISSUE THREAD

**Issue by AurastiX** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#29]
Hello Ahmed, 

as i was trying using your course downloader - im getting always the failure "failed to extrace a course video - the provided Token is probably invalid" 

As tho im using it on windows and fully as your guide telling me im doint everything mentioned.. 

Do you have any ideas to that issue?

Thank you
AurastiX

**Comment by ahmedayman4a** [comment]
What kind of LinkedIn Learning account do you have? LinkedIn premium? library account? organization account?

**Comment by AurastiX** [comment]
I got an personal Account, do i need one of your mentioned accounts tho?

**Comment by ahmedayman4a** [comment]
LinkedIn learning is only available to LinkedIn Premium subscribers unfortunately or if your library provides a linkedin learning account.
