### ISSUE TITLE
LinkedIn Learning page does not load (Banned)

### ISSUE THREAD

**Issue by vxlkiria50** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#37]
**Describe the bug**
I was about to download a course (i did not buy the courses, i got plus subscription) then when i was about to copy the course link suddenly the page did not charge it went blank. i tried to refresh the page several times but it did not worked. I don't know if it's the platform error, because I've tried my account on other platforms like brave and edge. The learning page does not load, but the other platforms do. I did it with the chrome version.
I hope the learning platform has not banned me. 
Windows 11

**Log File**
[log20220316.txt](https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/files/8265009/log20220316.txt)

![image](https://user-images.githubusercontent.com/101525207/158635527-ed7c6ac2-7dba-4efe-b96d-ef48d29f095f.png)

**Comment by ahmedayman4a** [comment]
So LinkedIn learning works on edge and brave but doesn't work on chrome correct?

**Comment by vxlkiria50** [comment]
> So LinkedIn learning works on edge and brave but doesn't work on chrome correct?

no, it doesn't work on any of them if im logged in (currently it works if im in incognito mode without my account logged in). i thought it was just chrome. I am worried that I have been banned. I'm going to wait until tomorrow to see if linkedin learning works again
![image](https://user-images.githubusercontent.com/101525207/158664791-0c2d7cac-58ac-4377-8d81-b3f496a0ab7c.png)

**Comment by vxlkiria50** [comment]
ok btw it just was a bug. If you download a lot of books (+25) i can say that linkedin will get bugget. It works very well now after 12 hours
![image](https://user-images.githubusercontent.com/101525207/158730638-1c15118e-468d-4671-8edb-22d39a0f5318.png)

**Comment by ahmedayman4a** [comment]
That's great. Glad it works now.

**Comment by ahmedayman4a** [comment]
To prevent this issue from happening, don't download a lot of courses at the same time and use the delay video extractions option,
