### ISSUE TITLE
Downloading course for organizational users

### ISSUE THREAD

**Issue by sandarbhasthana** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#40]
I'm using LinkedIn Learning from my Sunnyvale Public Library Card and although the app is able to extract the token but unable to download the course citing wrong login credentials.

I understand as the application checks the login page at URL; "linkedin.com/learning" but for organizations, it comes under

**Login > Sign in with your library card > "Textbox to enter the library ID" > Username : Password**

Can you please add this feature as it would be really helpful for people like us to learn while being offline?

Thanks!

**Comment by ahmedayman4a** [comment]
The app works with library accounts. I have tested it myself. Does this issue happen with all courses? If it does, could you try getting the token manually like this :

* **Firefox**

1. Press `Shift+F9` on your keyboard **OR** right click anywhere on the LinkedIn Learning website , choose "Inspect Element" and click storage.
2. Look for the word "li_at" in the column "Name". Copy the value and paste it in the program.

![LinkedIn Firefox Token Tutorial GIF](https://raw.githubusercontent.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/main/LLCD.DownloaderGUI/img/LinkedinFirefoxTokenTutorial-min.gif)

* **Google Chrome**

1. Right click anywhere on the page and click inspect element **OR** press `F12` on your keyboard
2. Click on the 2 arrows in the top right corner beside the word performance then click Application
3. Double click on the word "Cookies" then click on https://www.linkedin.com
4. Look for the word "li_at" in the column "Name". Copy the value and paste it in the program.

![LinkedIn Chrome Token Tutorial](https://raw.githubusercontent.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/main/LLCD.DownloaderGUI/img/LinkedinChromeTokenTutorial.gif)

**Comment by sandarbhasthana** [comment]
Hi,

I've was trying it through Chrome and the Cookies section was empty even for logged in user but on Firefox I was able to get the token and download the course.

Thanks a lot!!!
