### ISSUE TITLE
Login Token

### ISSUE THREAD

**Issue by mukuha** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#52]
How can I get the token cookie if don't have an account?

**Comment by ahmedayman4a** [comment]
No, unfortunately you can't. You need a premium linkedin account. But if you live in USA, many public libraries offer free linkedin learning accounts with their online signup.

**Comment by mukuha** [comment]
I found a token. The most recent app don't use english? the user interface? how can I change it to english?

**Comment by ahmedayman4a** [comment]
Issue mentioned at #42. Here is my response to this issue:
Can you try uninstalling the quicksand font from your computer and rerunning the app. Don't worry, you can reinstall it easily.
A font file could also be corrupt. Could you try uninstalling the app then redownloading the app from [here](https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/releases) and installing it.

**Comment by mukuha** [comment]
Thank you! Uninstalling and reinstalling quicksand worked.
