### ISSUE TITLE
Linkedin-Learning-Courses-Downloader

### ISSUE THREAD

**Issue by notepad185** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#6]
Hi Im afraid the Linkedin-Learning-Courses-Downloader
at https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader doesn't work
made sure I had the correct token etc in all three browsers but it cant download the Video. Maybe linked-in have changed something?
any chance you can fix it?

thanks for all your effort
best wishes R.

**Comment by ahmedayman4a** [comment]
I have just tried running the app and it works fine.
What operating system are you using?
If you are on windows, go to `%localappdata%\Linkedin-Learning-Courses-Downloader\app-1.1.0\logs` and upload the most recent log files here

**Comment by notepad185** [comment]
Must be something im doing wrong?

[log20210517.txt](https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/files/6495806/log20210517.txt)

Thanks for your help
R

**Comment by notepad185** [comment]
Hi Ahmed I sent the log file to you on github.Just wondered if you are able to help me get it working. Kindest regards Ray On 17 May 2021 17:11, Ahmed Ayman ***@***.***> wrote:
I have just tried running the app and it works fine.
What operating system are you using?
If you are on windows, go to %localappdata%\Linkedin-Learning-Courses-Downloader\app-1.1.0\logs and upload the most recent log files here

**Comment by ahmedayman4a** [comment]
It seems that the problem is that the extractor can't access one or more videos of this course. 

- Can you make sure that you can access the videos on linkedin-learning with this account?
- How did you extract the authentication token? With the extract token button or manually?
- What kind of account do you have? Do you have an organization account like a library account or a normal private account?

**Comment by ahmedayman4a** [comment]
Yes, this downloader doesn't bypass the need for an account. Contact me at ahmedayman4a77@gmail.com. I have an extra account I don't use.
