### ISSUE TITLE
Feature Request - Time delay between video downloads

### ISSUE THREAD

**Issue by Iain-Bell** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#9]
Great program, been waiting for this.

1 small feature I would like to request is a time delay option between each video download.  I've heard the some training sites detect lots of downloads/multiple connections and ban/suspend users if detected (as they assume a ripper is being used).  I read Pluralsight is one of them and you need to pause the rippers for about 15 min per download to be sure you are not detected.

An even better option would be a (delay of x minutes) + (random time x seconds/minutes) so the time between each download is more randomized too.

I know most people prefer to download as fast possible, but I'd prefer the ability to do it slower and more stealthy :)

Again, great work.

**Comment by ahmedayman4a** [comment]
Maybe delay between video extractions then because the downloader doesn't use the user account only the extractor.

**Comment by nixsee** [comment]
Thanks for adding this. How do we use the delay in the linux command line? Also, if it could be randomized as suggested, that would be even better. I'd like to just leave this as a batch job on my vps server, which can download an entire course in 1 minute right now...
